Provide an URL to download pax if missing
(Old svn revision: 11728)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20264,8 +20264,8 @@ echo "${ECHO_T}no" >&6
 fi
 
 if test -z "$PAX"; then
-  { { echo "$as_me:$LINENO: error: pax not found" >&5
-echo "$as_me: error: pax not found" >&2;}
+  { { echo "$as_me:$LINENO: error: pax (the POSIX standard archive tool) is not found on your system, you can get a version from ftp://ftp.suse.com/pub/people/kukuk/pax/" >&5
+echo "$as_me: error: pax (the POSIX standard archive tool) is not found on your system, you can get a version from ftp://ftp.suse.com/pub/people/kukuk/pax/" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
